/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utub;


import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Developer
 */
public class Navegacion extends javax.swing.JPanel {

    /**
     * Creates new form Navegacion
     */
    public Navegacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nick = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mag.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("SISTEMA DE INFORMACIÓN EMAB ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Clave:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuario:");

        nick.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        pass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addComponent(nick, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         consultar();

    }//GEN-LAST:event_jButton1ActionPerformed

    
//    public String consultar2() throws HeadlessException {
//        String correcto = "";
//        try {
//            //se consulta  a la db si el usuario es valido
//            Conexion c = new Conexion();
//            ResultSet rs;
//            Map parametros = new HashMap();
//
//            String sql = "SELECT * FROM emab.usuario u \n"
//                    + "where u.nick = ?\n"
//                    + "and u.contraseña = ?;";
//            char[] contra = pass.getPassword();
//            String passString = new String(contra);
//            parametros.put(1, this.nick.getText().trim());
//            parametros.put(2, passString);
//            rs = c.consultarDB(sql, parametros);
//            while (rs.next()) {
//                correcto = rs.getString("rol");
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Navegacion.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return correcto;
//    }
//    
//    public boolean consultar() throws HeadlessException {
//        boolean correcto = false;
//        try {
//            //se consulta  a la db si el usuario es valido
//            Conexion c = new Conexion();
//            ResultSet rs;
//            Map parametros = new HashMap();
//
//            String sql = "SELECT * FROM emab.usuario u \n"
//                    + "where u.nick = ?\n"
//                    + "and u.contraseña = ?;";
//            char[] contra = pass.getPassword();
//            String passString = new String(contra);
//            parametros.put(1, this.nick.getText().trim());
//            parametros.put(2, passString);
//            rs = c.consultarDB(sql, parametros);
//            while (rs.next()) {
//                correcto = true;
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(Navegacion.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return correcto;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nick;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables

    void addButton1ActionListener(ActionListener actionListener) {
        jButton1.addActionListener(actionListener);
    }

}
